flowchart TD
A[Realidad]
B[Causa-efecto]
C[Lógica]
D[Programación]

E[Cerebros]
F[Sociedad]

G[Lenguaje natural]
H[Lenguaje lógico]
I[NaturalScript]

A --que funciona por--> B
B --que se estudia por la-->C
D --que incluye-->C

E --hacen funcionar a la-->F
F --que es parte de la-->A

E --funcionan con-->G
D --funciona con-->H

subgraph Esto:
I --usa-->G
I --usa-->H
end
